//
// Generated file, do not edit! Created by opp_msgtool 6.3 from apps/PublisherTimeTag.msg.
//

#ifndef __INET_PUBLISHERTIMETAG_M_H
#define __INET_PUBLISHERTIMETAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace inet {

class PublisherTimeTag;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/TagBase_m.h" // import inet.common.TagBase


namespace inet {

/**
 * Class generated from <tt>apps/PublisherTimeTag.msg:23</tt> by opp_msgtool.
 * <pre>
 * class PublisherTimeTag extends TagBase
 * {
 *     simtime_t publisherTime;  // Example field
 * }
 * </pre>
 */
class PublisherTimeTag : public ::inet::TagBase
{
  protected:
    ::omnetpp::simtime_t publisherTime = SIMTIME_ZERO;

  private:
    void copy(const PublisherTimeTag& other);

  protected:
    bool operator==(const PublisherTimeTag&) = delete;

  public:
    PublisherTimeTag();
    PublisherTimeTag(const PublisherTimeTag& other);
    virtual ~PublisherTimeTag();
    PublisherTimeTag& operator=(const PublisherTimeTag& other);
    virtual PublisherTimeTag *dup() const override {return new PublisherTimeTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual ::omnetpp::simtime_t getPublisherTime() const;
    virtual void setPublisherTime(::omnetpp::simtime_t publisherTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PublisherTimeTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PublisherTimeTag& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::PublisherTimeTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::PublisherTimeTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_PUBLISHERTIMETAG_M_H

